import { sql } from "drizzle-orm";
import { boolean, integer, jsonb, pgTable, text, timestamp, uniqueIndex } from "drizzle-orm/pg-core";

export const instruments = pgTable(
  "instruments",
  {
    id: text("id").primaryKey(),
    etoroInstrumentId: integer("etoro_instrument_id"),
    canonicalSymbol: text("canonical_symbol").notNull(),
    displayName: text("display_name").notNull(),
    assetClass: text("asset_class"),
    pricePrecision: integer("price_precision"),
    enabled: boolean("enabled").notNull().default(true),
    metadataJson: jsonb("metadata_json"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [uniqueIndex("instruments_canonical_symbol_idx").on(table.canonicalSymbol)],
);

export const accountSnapshots = pgTable("account_snapshots", {
  id: text("id").primaryKey(),
  timestamp: timestamp("timestamp", { withTimezone: true }).notNull(),
  accountType: text("account_type").notNull(),
  equity: text("equity"),
  cash: text("cash"),
  availableCash: text("available_cash"),
  invested: text("invested"),
  unrealizedPnl: text("unrealized_pnl"),
  realizedDailyPnl: text("realized_daily_pnl"),
  openPositionCount: integer("open_position_count"),
  rawPayloadJson: jsonb("raw_payload_json"),
});

export const candles = pgTable(
  "candles",
  {
    id: text("id").primaryKey(),
    instrumentId: text("instrument_id").notNull(),
    timeframe: text("timeframe").notNull(),
    openTimeUtc: timestamp("open_time_utc", { withTimezone: true }).notNull(),
    closeTimeUtc: timestamp("close_time_utc", { withTimezone: true }).notNull(),
    open: text("open").notNull(),
    high: text("high").notNull(),
    low: text("low").notNull(),
    close: text("close").notNull(),
    volume: text("volume"),
    source: text("source").notNull(),
    isFinal: boolean("is_final").notNull(),
    revision: integer("revision").notNull().default(0),
  },
  (table) => [uniqueIndex("candles_instrument_tf_open_idx").on(table.instrumentId, table.timeframe, table.openTimeUtc)],
);

export const indicatorSnapshots = pgTable(
  "indicator_snapshots",
  {
    id: text("id").primaryKey(),
    instrumentId: text("instrument_id").notNull(),
    timeframe: text("timeframe").notNull(),
    candleOpenTime: timestamp("candle_open_time", { withTimezone: true }).notNull(),
    rsi14: text("rsi14"),
    atr14: text("atr14"),
    ema20: text("ema20"),
    ema50: text("ema50"),
    ema200: text("ema200"),
    bbBasis20: text("bb_basis20"),
    bbUpper20x2: text("bb_upper20x2"),
    bbLower20x2: text("bb_lower20x2"),
    bbWidth: text("bb_width"),
    trueRange: text("true_range"),
    rollingVolatility: text("rolling_volatility"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex("indicator_snapshots_instrument_tf_open_idx").on(
      table.instrumentId,
      table.timeframe,
      table.candleOpenTime,
    ),
  ],
);

export const auditLogs = pgTable("audit_logs", {
  id: text("id").primaryKey(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  eventType: text("event_type").notNull(),
  requestId: text("request_id"),
  instrumentId: text("instrument_id"),
  payloadJson: jsonb("payload_json"),
});

export const pivots = pgTable(
  "pivots",
  {
    id: text("id").primaryKey(),
    instrumentId: text("instrument_id").notNull(),
    timeframe: text("timeframe").notNull(),
    openTimeUtc: timestamp("open_time_utc", { withTimezone: true }).notNull(),
    type: text("type").notNull(),
    price: text("price").notNull(),
    leftBars: integer("left_bars").notNull(),
    rightBars: integer("right_bars").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [uniqueIndex("pivots_instrument_tf_open_type_idx").on(table.instrumentId, table.timeframe, table.openTimeUtc, table.type)],
);

export const priceZones = pgTable("price_zones", {
  id: text("id").primaryKey(),
  instrumentId: text("instrument_id").notNull(),
  timeframe: text("timeframe").notNull(),
  type: text("type").notNull(),
  source: text("source").notNull(),
  lowerBound: text("lower_bound").notNull(),
  upperBound: text("upper_bound").notNull(),
  midpoint: text("midpoint").notNull(),
  strengthScore: integer("strength_score").notNull(),
  touchCount: integer("touch_count").notNull(),
  lastTouchedAt: timestamp("last_touched_at", { withTimezone: true }),
  status: text("status").notNull(),
  metadataJson: jsonb("metadata_json"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const marketRegimes = pgTable(
  "market_regimes",
  {
    id: text("id").primaryKey(),
    instrumentId: text("instrument_id").notNull(),
    timeframe: text("timeframe").notNull(),
    timestamp: timestamp("timestamp", { withTimezone: true }).notNull(),
    trend: text("trend").notNull(),
    structure: text("structure").notNull(),
    volatility: text("volatility").notNull(),
    location: text("location").notNull(),
    confidence: integer("confidence").notNull(),
    evidenceJson: jsonb("evidence_json"),
  },
  (table) => [uniqueIndex("market_regimes_instrument_tf_ts_idx").on(table.instrumentId, table.timeframe, table.timestamp)],
);

export const signals = pgTable(
  "signals",
  {
    id: text("id").primaryKey(),
    instrumentId: text("instrument_id").notNull(),
    symbol: text("symbol").notNull(),
    strategyKey: text("strategy_key").notNull(),
    strategyVersion: text("strategy_version").notNull(),
    direction: text("direction").notNull(),
    state: text("state").notNull(),
    triggerTimeframe: text("trigger_timeframe").notNull(),
    detectedAt: timestamp("detected_at", { withTimezone: true }).notNull(),
    watchingAt: timestamp("watching_at", { withTimezone: true }),
    confirmedAt: timestamp("confirmed_at", { withTimezone: true }),
    tradePlannedAt: timestamp("trade_planned_at", { withTimezone: true }),
    invalidatedAt: timestamp("invalidated_at", { withTimezone: true }),
    expiredAt: timestamp("expired_at", { withTimezone: true }),
    dismissedAt: timestamp("dismissed_at", { withTimezone: true }),
    enteredAt: timestamp("entered_at", { withTimezone: true }),
    closedAt: timestamp("closed_at", { withTimezone: true }),
    score: integer("score").notNull(),
    confidenceLabel: text("confidence_label").notNull(),
    entryZoneLow: text("entry_zone_low"),
    entryZoneHigh: text("entry_zone_high"),
    invalidationPrice: text("invalidation_price"),
    target1: text("target1"),
    target2: text("target2"),
    target3: text("target3"),
    riskRewardToT1: text("risk_reward_to_t1"),
    riskRewardToT2: text("risk_reward_to_t2"),
    lastEvaluatedOpenTimeUtc: timestamp("last_evaluated_open_time_utc", { withTimezone: true }).notNull(),
    evidenceJson: jsonb("evidence_json"),
    snapshotJson: jsonb("snapshot_json"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex("signals_open_identity_idx")
      .on(table.instrumentId, table.strategyKey, table.direction)
      .where(sql`${table.state} not in ('INVALIDATED', 'EXPIRED', 'DISMISSED', 'CLOSED')`),
  ],
);

export const alerts = pgTable(
  "alerts",
  {
    id: text("id").primaryKey(),
    type: text("type").notNull(),
    instrumentId: text("instrument_id").notNull(),
    symbol: text("symbol").notNull(),
    signalId: text("signal_id"),
    zoneId: text("zone_id"),
    title: text("title").notNull(),
    body: text("body").notNull(),
    score: integer("score"),
    direction: text("direction"),
    state: text("state"),
    dedupeKey: text("dedupe_key").notNull(),
    channelsJson: jsonb("channels_json").notNull(),
    readAt: timestamp("read_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [uniqueIndex("alerts_dedupe_key_idx").on(table.dedupeKey)],
);

export const appSettings = pgTable("app_settings", {
  id: text("id").primaryKey(),
  alertsJson: jsonb("alerts_json").notNull(),
  riskJson: jsonb("risk_json").notNull(),
  marketsJson: jsonb("markets_json").notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const brokerPositions = pgTable(
  "broker_positions",
  {
    id: text("id").primaryKey(),
    etoroPositionId: text("etoro_position_id").notNull(),
    instrumentId: integer("instrument_id").notNull(),
    symbol: text("symbol"),
    direction: text("direction").notNull(),
    openedAt: timestamp("opened_at", { withTimezone: true }),
    openPrice: text("open_price"),
    units: text("units"),
    investedAmount: text("invested_amount"),
    leverage: text("leverage"),
    stopLoss: text("stop_loss"),
    takeProfit: text("take_profit"),
    unrealizedPnl: text("unrealized_pnl"),
    fees: text("fees"),
    mirrorId: integer("mirror_id").notNull().default(0),
    rawPayloadJson: jsonb("raw_payload_json"),
    syncedAt: timestamp("synced_at", { withTimezone: true }).notNull(),
  },
  (table) => [uniqueIndex("broker_positions_etoro_id_idx").on(table.etoroPositionId)],
);

export const brokerTrades = pgTable(
  "broker_trades",
  {
    id: text("id").primaryKey(),
    etoroPositionId: text("etoro_position_id").notNull(),
    etoroOrderId: text("etoro_order_id"),
    instrumentId: integer("instrument_id").notNull(),
    symbol: text("symbol"),
    direction: text("direction").notNull(),
    openedAt: timestamp("opened_at", { withTimezone: true }),
    closedAt: timestamp("closed_at", { withTimezone: true }),
    openPrice: text("open_price"),
    closePrice: text("close_price"),
    units: text("units"),
    investedAmount: text("invested_amount"),
    leverage: text("leverage"),
    stopLoss: text("stop_loss"),
    takeProfit: text("take_profit"),
    realizedPnl: text("realized_pnl"),
    fees: text("fees"),
    sourceAccount: text("source_account").notNull(),
    rawBrokerPayloadJson: jsonb("raw_broker_payload_json"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [uniqueIndex("broker_trades_etoro_account_idx").on(table.etoroPositionId, table.sourceAccount)],
);

export const tradePlans = pgTable("trade_plans", {
  id: text("id").primaryKey(),
  signalId: text("signal_id").notNull(),
  accountSnapshotId: text("account_snapshot_id"),
  direction: text("direction").notNull(),
  entryType: text("entry_type").notNull(),
  plannedEntry: text("planned_entry"),
  stopLoss: text("stop_loss"),
  target1: text("target1"),
  target2: text("target2"),
  target3: text("target3"),
  riskPct: text("risk_pct"),
  riskAmountUsd: text("risk_amount_usd"),
  estimatedPositionSize: text("estimated_position_size"),
  expectedR: text("expected_r"),
  gateStatus: text("gate_status").notNull(),
  blockReasonsJson: jsonb("block_reasons_json"),
  checklistJson: jsonb("checklist_json"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  approvedAt: timestamp("approved_at", { withTimezone: true }),
});

export const riskState = pgTable("risk_state", {
  id: text("id").primaryKey(),
  consecutiveLosses: integer("consecutive_losses").notNull(),
  lastLossAt: timestamp("last_loss_at", { withTimezone: true }),
  cooldownUntil: timestamp("cooldown_until", { withTimezone: true }),
  manualCooldownUntil: timestamp("manual_cooldown_until", { withTimezone: true }),
  dailyPnl: text("daily_pnl").notNull(),
  tradingStatus: text("trading_status").notNull(),
  historyUnavailable: boolean("history_unavailable").notNull().default(false),
  lastSyncAt: timestamp("last_sync_at", { withTimezone: true }),
  lastSyncLatencyMs: integer("last_sync_latency_ms"),
  syncErrorCount: integer("sync_error_count").notNull().default(0),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const economicEvents = pgTable("economic_events", {
  id: text("id").primaryKey(),
  eventName: text("event_name").notNull(),
  currency: text("currency").notNull(),
  impact: text("impact").notNull(),
  scheduledAtUtc: timestamp("scheduled_at_utc", { withTimezone: true }).notNull(),
  blackoutBeforeMinutes: integer("blackout_before_minutes").notNull(),
  blackoutAfterMinutes: integer("blackout_after_minutes").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const journalEntries = pgTable(
  "journal_entries",
  {
    id: text("id").primaryKey(),
    etoroPositionId: text("etoro_position_id").notNull(),
    brokerTradeId: text("broker_trade_id"),
    tradePlanId: text("trade_plan_id"),
    signalId: text("signal_id"),
    setupKey: text("setup_key"),
    matchStatus: text("match_status").notNull(),
    matchLocked: boolean("match_locked").notNull().default(false),
    symbol: text("symbol"),
    instrumentId: integer("instrument_id"),
    direction: text("direction").notNull(),
    openedAt: timestamp("opened_at", { withTimezone: true }),
    closedAt: timestamp("closed_at", { withTimezone: true }),
    openPrice: text("open_price"),
    closePrice: text("close_price"),
    units: text("units"),
    realizedPnl: text("realized_pnl"),
    fees: text("fees"),
    thesisText: text("thesis_text"),
    preTradeEmotion: text("pre_trade_emotion"),
    postTradeEmotion: text("post_trade_emotion"),
    followedPlan: boolean("followed_plan"),
    ruleBreaksJson: jsonb("rule_breaks_json"),
    maeUsd: text("mae_usd"),
    maeR: text("mae_r"),
    mfeUsd: text("mfe_usd"),
    mfeR: text("mfe_r"),
    resultR: text("result_r"),
    notes: text("notes"),
    screenshotUrl: text("screenshot_url"),
    tagsJson: jsonb("tags_json"),
    alignedWithTrend: boolean("aligned_with_trend"),
    snapshotJson: jsonb("snapshot_json"),
    evidenceJson: jsonb("evidence_json"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex("journal_entries_etoro_position_idx").on(table.etoroPositionId),
    uniqueIndex("journal_entries_trade_plan_idx")
      .on(table.tradePlanId)
      .where(sql`${table.tradePlanId} is not null`),
  ],
);
