export const STRUCTURE_DEFAULTS = {
  leftBars: 3,
  rightBars: 3,
  equalToleranceAtr: "0.10",
  clusterAtrFraction: "0.25",
  breakPenetrationAtr: "0.15",
  locationAtr: "0.25",
  extendedAtr: "1.0",
  expireIdleBars: 200,
  expireStrengthBelow: 20,
  volatilityLookback: 50,
  volatilityLow: "0.7",
  volatilityHigh: "1.3",
  volatilityExtreme: "2.0",
  wickRejectionRatio: "0.6",
  engulfingBodyAtr: "0.8",
  reactionAtr: "0.5",
  recentTouchBars: 20,
  rsiResetOversold: "30",
  rsiResetOversoldExit: "35",
  rsiResetOverbought: "70",
  rsiResetOverboughtExit: "65",
} as const;
